# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'deliveries_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for deliveries_iOS
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireObjectMapper', '~> 4.1'
    pod 'SwiftyJSON', '~> 3.1'
    pod 'SnapKit', '~> 3.2'
    pod 'ESPullToRefresh', '~> 2.6'
    
  target 'deliveries_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'deliveries_iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
